/**
 * wh40k10e — Tamagui Theme Partial (generated)
 *
 * Auto-generated by @armoury/theme-generator. DO NOT EDIT.
 * Source: src/systems/wh40k10e/src/public/tokens.ts
 *
 * Provides light and dark theme objects for Tamagui createTheme.
 * Color values are oklch strings resolved at runtime by the platform.
 */

/** Light mode theme tokens for Tamagui. */
export const wh40k10eLight = {
    primary: 'oklch(0.48 0.1 55)',
    primaryHover: 'oklch(0.42 0.11 55)',
    primaryMuted: 'oklch(0.48 0.1 55 / 12%)',
    primaryForeground: 'oklch(0.98 0.005 55)',
    highlight: 'oklch(0.46 0.18 25)',
    highlightHover: 'oklch(0.4 0.19 25)',
    highlightMuted: 'oklch(0.46 0.18 25 / 12%)',
    highlightForeground: 'oklch(0.98 0.005 25)',
    background: 'oklch(0.96 0.006 60)',
    ring: 'oklch(0.48 0.1 55 / 40%)',
    shadowGlow: '0 0 0 3px oklch(0.48 0.1 55 / 20%)',
} as const;

/** Dark mode theme tokens for Tamagui. */
export const wh40k10eDark = {
    primary: 'oklch(0.72 0.1 55)',
    primaryHover: 'oklch(0.78 0.11 55)',
    primaryMuted: 'oklch(0.72 0.1 55 / 18%)',
    primaryForeground: 'oklch(0.15 0.01 55)',
    highlight: 'oklch(0.62 0.2 25)',
    highlightHover: 'oklch(0.68 0.21 25)',
    highlightMuted: 'oklch(0.62 0.2 25 / 18%)',
    highlightForeground: 'oklch(0.15 0.01 25)',
    background: 'oklch(0.18 0.008 50)',
    ring: 'oklch(0.72 0.1 55 / 40%)',
    shadowGlow: '0 0 12px oklch(0.72 0.1 55 / 15%)',
} as const;
