services:
    authorizer:
        path: src/services/authorizer
    campaigns:
        path: src/services/campaigns
        params:
            authorizerArn: ${authorizer.AuthorizerArn}
    matches:
        path: src/services/matches
        params:
            authorizerArn: ${authorizer.AuthorizerArn}
    friends:
        path: src/services/friends
        params:
            authorizerArn: ${authorizer.AuthorizerArn}
    users:
        path: src/services/users
        params:
            authorizerArn: ${authorizer.AuthorizerArn}
