name: Campaigns Sandbox Cleanup

on:
    pull_request:
        types: [closed]
        branches: [main]
        paths:
            - 'src/services/campaigns/**'
            - 'src/shared/**'

jobs:
    cleanup:
        uses: ./.github/workflows/_cleanup-service.yml
        with:
            working-directory: src/services/campaigns
            service-short-name: campaigns
            routing-rule-priority: 200
        secrets: inherit
