name: Matches Service

on:
    push:
        branches: [main]
        paths:
            - 'src/services/matches/**'
            - 'src/shared/**'
    pull_request:
        branches: [main]
        paths:
            - 'src/services/matches/**'
            - 'src/shared/**'

concurrency:
    group: matches-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        uses: ./.github/workflows/_deploy-service.yml
        with:
            service-name: '@armoury/matches'
            working-directory: src/services/matches
            needs-shared-build: true
            has-migrations: false
        secrets: inherit
