name: Web

on:
    push:
        branches: [main]
        paths:
            - 'src/web/**'
            - 'src/shared/**'
            - 'src/systems/**'
            - 'e2e/web/**'
            - '.browserslistrc'
    pull_request:
        branches: [main]
        paths:
            - 'src/web/**'
            - 'src/shared/**'
            - 'src/systems/**'
            - 'e2e/web/**'
            - '.browserslistrc'

concurrency:
    group: web-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci:
        uses: ./.github/workflows/_ci-web.yml

    e2e:
        needs: ci
        uses: ./.github/workflows/_e2e-web.yml
        secrets: inherit
